name: Test

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
<<<<<<< HEAD
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
=======
      - name: Use Node.js 26.x
        uses: actions/setup-node@v1
        with:
          node-version: 26.x
>>>>>>> main
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test